/**
 * Regenerate public/sitemap.xml, including a URL for every WPBL player.
 *
 * The file used to be written by hand, which was fine for five URLs and is not fine for a
 * hundred and twenty. It was also quietly lying: every entry claimed `changefreq: hourly`
 * and a `lastmod` of the day the file was created, for pages that had not changed since.
 *
 * The tab paths come from src/wpbl/routes.ts rather than being restated here, so a new tab
 * cannot be added to the app and forgotten in the sitemap. That is also what
 * src/wpbl/__tests__/routes.test.ts pins.
 *
 *   npm run sitemap
 *
 * Needs VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (both public, both already in the
 * client bundle). Reads only; writes nothing but the file.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { WPBL_VIEW_PATHS, WPBL_PLAYERS_BASE, wpblPlayerSlug, type WpblSluggable } from '../src/wpbl/routes'
import { slugifyName } from '../src/wpbl/slug'

const SITE = 'https://sportydolphin.fun'
// Relative to the repo root, NOT to this file: `npm run sitemap` bundles it into
// node_modules/.cache first, so import.meta.url points somewhere useless by the time it runs.
const OUT = resolve(process.cwd(), 'public', 'sitemap.xml')

interface Entry { loc: string; changefreq: string; priority: string }

// The pages that exist regardless of what is in the database. Priorities are relative to
// each other and to nothing else: WPBL is the section the site leads with, the legal pages
// are here only so they are not orphaned.
const STATIC: Entry[] = [
  { loc: '/wpbl', changefreq: 'hourly', priority: '1.0' },
  { loc: '/wpbl/standings', changefreq: 'daily', priority: '0.9' },
  { loc: '/wpbl/stats', changefreq: 'daily', priority: '0.9' },
  { loc: '/wpbl/schedule', changefreq: 'daily', priority: '0.8' },
  { loc: '/wpbl/teams', changefreq: 'weekly', priority: '0.8' },
  { loc: `${WPBL_PLAYERS_BASE}`, changefreq: 'weekly', priority: '0.8' },
  { loc: '/mlb', changefreq: 'hourly', priority: '0.8' },
  { loc: '/wpbl/api', changefreq: 'weekly', priority: '0.5' },
  { loc: '/privacy', changefreq: 'yearly', priority: '0.2' },
  { loc: '/terms', changefreq: 'yearly', priority: '0.2' },
]

async function readRoster(): Promise<WpblSluggable[]> {
  const base = process.env.VITE_SUPABASE_URL
  const key = process.env.VITE_SUPABASE_ANON_KEY
  if (!base || !key) {
    throw new Error('VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are required (try: node --env-file=.env)')
  }
  const res = await fetch(`${base.replace(/\/+$/, '')}/rest/v1/wpbl_players?select=id,name&order=name.asc`, {
    headers: { apikey: key, authorization: `Bearer ${key}`, accept: 'application/json' },
  })
  if (!res.ok) throw new Error(`postgrest ${res.status}`)
  return (await res.json()) as WpblSluggable[]
}

function xml(entries: Entry[], lastmod: string): string {
  const urls = entries.map(e => `  <url>
    <loc>${SITE}${e.loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority}</priority>
  </url>`).join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.ts (npm run sitemap). Do not hand-edit: the player
     URLs come from the roster, and a hand edit is lost on the next run. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
}

const roster = await readRoster()

// Loud on purpose. A shared name is the one case where a player's URL is not simply their
// name, and it is otherwise invisible: both players still get a working page, but at
// suffixed URLs, and anyone who linked the bare slug now has a dead link.
const byBase = new Map<string, string[]>()
for (const p of roster) {
  const b = slugifyName(p.name)
  byBase.set(b, [...(byBase.get(b) ?? []), p.name])
}
const collisions = [...byBase.entries()].filter(([, names]) => names.length > 1)
if (collisions.length) {
  console.warn(`\n  ${collisions.length} shared name(s); these players get id-suffixed URLs:`)
  for (const [base, names] of collisions) console.warn(`    ${base}: ${names.join(', ')}`)
  console.warn('')
}

const players: Entry[] = roster.map(p => ({
  loc: `${WPBL_PLAYERS_BASE}/${wpblPlayerSlug(p, roster)}`,
  changefreq: 'daily',
  priority: '0.7',
}))

// Guard against the tab list and this file drifting apart. The test pins the sitemap's
// CONTENTS, but only this can catch a tab that exists and was never given an entry.
const missing = WPBL_VIEW_PATHS.filter(p => !STATIC.some(e => e.loc === p))
if (missing.length) throw new Error(`WPBL tabs missing from STATIC: ${missing.join(', ')}`)

const lastmod = new Date().toISOString().slice(0, 10)
writeFileSync(OUT, xml([...STATIC, ...players], lastmod), 'utf8')
console.log(`sitemap: ${STATIC.length + players.length} URLs (${players.length} players) -> public/sitemap.xml`)
